init: Cargo.dev.toml
	git config --local user.email xian81144177@163.com
	git config --local user.name pk-wei
	cp Cargo.dev.toml Cargo.toml

push:
	git push origin -u main

build:
	cargo build --release

push:

	git push -u origin main
